CREATE TABLE user_balances (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    balance_amount BIGINT DEFAULT 0 NOT NULL,
    currency VARCHAR(3) DEFAULT 'IDR' NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);